### ISSUE TITLE
Pretrained models of PointNet++ cannot be extracted

### ISSUE THREAD

**Issue by 990706TJGU** [facebookresearch/DepthContrast#10]
Hello, I tried to download the models from links of Model Zoo, but none of these files can be extracted.
Can you help to analyze the reason?
Many thanks！

**Comment by zaiweizhang** [comment]
Yes. Those files are pytorch checkpoint files. 
You will need to load with pytorch library. Like the following:
model = torch.load(PATH)

**Comment by 990706TJGU** [comment]
Thanks for your reply!
Can you reveal which pytorch version did you use for this project?

**Comment by zaiweizhang** [comment]
We used pytorch 1.5. All the required packages are listed [here](https://github.com/facebookresearch/DepthContrast/blob/main/requirements.txt).
