### ISSUE TITLE
Only one scene loaded by reader.py for preparing Scannet dataset

### ISSUE THREAD

**Issue by rishabhgks** [facebookresearch/DepthContrast#15]
Hi,
I have downloaded the Scannet dataset.
Now I am following the instruction in the readme file to run the reader.py file to extract the depth images and other related info from the .sens file.
However I noticed that the reader.py file is only processing one file from the scannet dataset:
```
def main():
  scans = glob(opt.scans_path+"/*")
  for scan in scans:
    scenename = scan.split("/")[-1]
    if scenename != "scene0000_00":
      continue
    filename = os.path.join(scan, scenename+".sens")
```
Here the if condition makes sure only one .sens file is processed.
Is this intentional or a debug statement that has to be commented out for processing the whole dataset?
And if this is intentional then could you take some time out to explain the reasoning behind it?
I am not very familiar with the scannet dataset

**Comment by zaiweizhang** [comment]
My mistake. This is a bug. I was testing the script and intentionally set it. It has been fixed now.

**Comment by rishabhgks** [comment]
No worries.
That's perfect
Thank you for getting back so quickly!
