### ISSUE TITLE
Trainining curve for ScanNet

### ISSUE THREAD

**Issue by BestSonny** [facebookresearch/DepthContrast#17]
@zaiweizhang  Is it possible that you could share the training curve for the ScanNet or point to me when it indicates a good converging point (e.g., the final converged loss values). Just curious about how it looks like as I am training it as well.  Thank you very much.

**Comment by zaiweizhang** [comment]
Yes. Here is a training loss curve plot. NPID is the single format loss curve, npid_cmc is the across format loss.
![temp](https://user-images.githubusercontent.com/32721297/117758974-97aa9500-b1e8-11eb-970f-d56c22e7eabf.png)
