### ISSUE TITLE
KITTI data splits

### ISSUE THREAD

**Issue by baraujo98** [facebookresearch/DepthContrast#20]
Did you use any special method for generating the training splits for KITTI or are they just randomly sampled from the dataset?

For exemple: are `kitti_infos_train_5_0.pkl`, `kitti_infos_train_5_1.pkl` and `kitti_infos_train_5_2.pkl` just 3 different sets of labels for a random 5% of the pointclouds?

Thanks

**Comment by zaiweizhang** [comment]
They are just randomly generated. And yes, those are just three random splits.

**Comment by baraujo98** [comment]
Nice! Thanks

**Comment by baraujo98** [comment]
Sorry to bother, @zaiweizhang, but by any chance, do you still have the script you used to generate these data splits? I'm thinking of making some of my own, maybe even reducing the percentage of labels.

**Comment by baraujo98** [comment]
No luck, @zaiweizhang? :grin:

**Comment by zaiweizhang** [comment]
Sorry, I was away for a couple of weeks. Yeah, I do not have the script. I think I just load the original kitti_infos list and then random select a portion of the training instances.
