### ISSUE TITLE
Install requirements for pip

### ISSUE THREAD

**Issue by BjoernMichele** [facebookresearch/DepthContrast#24]
First, thank you for providing this well curated code base. 

I was just wondering, if the requirements.txt that you provide in DepthContrast/ is usable for an installation with pip?  

I think the requirements.txt  is one for a conda installation but as far as I know this can't be used with pip (correct me if I am wrong). It would probably save me and probably also other pip users a lot of work, if you could also provide a requirements for pip :).

**Comment by zaiweizhang** [comment]
Sorry, currently we only support conda installation.
