### ISSUE TITLE
Why apply slighter data augementation to LiDAR data?

### ISSUE THREAD

**Issue by yichen928** [facebookresearch/DepthContrast#25]
Hello, thank you for this excellent work.

I notice that you apply slighter data augmentation to LiDAR data than other point clouds, including:
1. yz-flip instead of xz-flip and yz-flip
2. [0.95, 1.05] random scale instead of [0.8, 1.2]
3. ±pi/4 rotation instead of ±pi

Can you tell me the reason about applying each slighter augmentation? Thank you very much!

**Comment by zaiweizhang** [comment]
Most of them are selected using hyper-parameter tuning based on the results, such as the random scale.
Although we have not tried xz-flip and yz-flip and larger rotation, feel free to try them yourself.
