### ISSUE TITLE
some question about lidar data augmentation

### ISSUE THREAD

**Issue by AndyYuan96** [facebookresearch/DepthContrast#30]
Hi, In https://github.com/facebookresearch/DepthContrast/blob/b8257890c94f7c58aeb5cefeb91af031692611d6/datasets/transforms/augment3d.py#L160, I just wonder why you keep all far points, but random select near point.

**Comment by zaiweizhang** [comment]
That's a common practice for Lidar point cloud sampling. E.g. it is used [here](https://github.com/open-mmlab/OpenPCDet) in a commonly used detection framework.

**Comment by AndyYuan96** [comment]
ok，thank you
