### ISSUE TITLE
Installing the requirements

### ISSUE THREAD

**Issue by baraujo98** [facebookresearch/DepthContrast#7]
Hi,

I found your work interesting and would like to run your code. However, I'm having some trouble installing the dependencies stated in `requirements.txt`. Some packages appear to be missing from the conda and conda-forge channels, but I think it might have to do with the way you exported the dependencies.

Would you be able to export the working environment using:
``conda env export --no-build > requirements.yaml``

Thanks!

**Comment by imisra** [comment]
@zaiweizhang - do you have a clean `conda` environment for this?

**Comment by imisra** [comment]
Attaching the conda environment file (it is a yaml file but github allows only the `.txt` extension)
[requirements.txt](https://github.com/facebookresearch/DepthContrast/files/6040194/requirements.txt)

**Comment by YanhaoWu** [comment]
> Attaching the conda environment file (it is a yaml file but github allows only the `.txt` extension) [requirements.txt](https://github.com/facebookresearch/DepthContrast/files/6040194/requirements.txt)

Hi! I tried to use this yaml file to install the environment. But many packages conflict with each other.
For example:
`Package pyqtwebengine conflicts for:
qtconsole=4.3.1 -> pyqt -> pyqtwebengine==5.12.1[build='py37he336c9b_5|py38h7400c14_6|py38h7400c14_7|py39h0fcd23e_7|py310hfcd6d55_8|py39h0fcd23e_8|py37he336c9b_8|py38h7400c14_8|py37he336c9b_7|py36h7ec31b9_7|py39h0fcd23e_6|py36h7ec31b9_6|py37he336c9b_6']
spyder=3.2.6 -> pyqt -> pyqtwebengine==5.12.1[build='py37he336c9b_5|py38h7400c14_6|py38h7400c14_7|py39h0fcd23e_7|py310hfcd6d55_8|py39h0fcd23e_8|py37he336c9b_8|py38h7400c14_8|py37he336c9b_7|py36h7ec31b9_7|py39h0fcd23e_6|py36h7ec31b9_6|py37he336c9b_6']
matplotlib=2.2.2 -> pyqt[version='>=5.6,<6.0a0'] -> pyqtwebengine==5.12.1[build='py37he336c9b_5|py38h7400c14_6|py38h7400c14_7|py39h0fcd23e_7|py310hfcd6d55_8|py39h0fcd23e_8|py37he336c9b_8|py38h7400c14_8|py37he336c9b_7|py36h7ec31b9_7|py39h0fcd23e_6|py36h7ec31b9_6|py37he336c9b_6']`

Is there any ways for this problem?
