### ISSUE TITLE
Pretraining on KITTI

### ISSUE THREAD

**Issue by baraujo98** [facebookresearch/DepthContrast#9]
Hi,

I'm thinking of performing a pretraining with KITTI, as I have limited computing resources, and using Waymo is out of my reach. 

Do you have any direction you can point me at, as to where in the code I should be looking to do those changes?

I've noticed you sugest the use of [RalphMao's repo](https://github.com/RalphMao/Waymo-Dataset-Tool) for batch downloading Waymo, which "converts the data into KITTI-like format". Do you think one feasible way would be to adapt your `extract_pointcloud.py` to extract from KITTI, for example?

Thanks in advance!

**Comment by zaiweizhang** [comment]
Yes. You just need to extract the point clouds and try our pretraining. I think there are lots of open source projects processing KITTI lidar point clouds.
I do not think you need to change anything.

**Comment by AndyYuan96** [comment]
> Yes. You just need to extract the point clouds and try our pretraining. I think there are lots of open source projects processing KITTI lidar point clouds.
> I do not think you need to change anything.

Hi, zaiwei, I just wonder how long you pretrain the pointRCNN model on waymo dataset(79K scan) with 8 V100 for example? I didn't see it in paper.
lidar point cloud consumes more resource than picture, so I just think batchsize=1024 consumes too much resource for me without too much gpu, and that is one reason that I think why pointContrast use point feature to do contrastive learning.

**Comment by AndyYuan96** [comment]
> Hi,
> 
> I'm thinking of performing a pretraining with KITTI, as I have limited computing resources, and using Waymo is out of my reach.
> 
> Do you have any direction you can point me at, as to where in the code I should be looking to do those changes?
> 
> I've noticed you sugest the use of [RalphMao's repo](https://github.com/RalphMao/Waymo-Dataset-Tool) for batch downloading Waymo, which "converts the data into KITTI-like format". Do you think one feasible way would be to adapt your `extract_pointcloud.py` to extract from KITTI, for example?
> 
> Thanks in advance!

Hi, from my point, I just think kitti dataset is too small for contrastive learning,  the result may be bad. If you have result on kitti with DepthContrast, looking foward to share with me, thanks.

**Comment by AndyYuan96** [comment]
> Yes. You just need to extract the point clouds and try our pretraining. I think there are lots of open source projects processing KITTI lidar point clouds.
> I do not think you need to change anything.

What's more, I just wonder why you choose batchsize=1024 to train, I see that you use MoCo's method to training, MoCo's batchsize is 256, does batchsize=256 is not good in pointcloud?

**Comment by AndyYuan96** [comment]
> Yes. You just need to extract the point clouds and try our pretraining. I think there are lots of open source projects processing KITTI lidar point clouds.
> I do not think you need to change anything.

what's more, for the result of pretrained on waymo and finetune on kitti, the pretrained weight's performance don't have too much different with random inited weight, it's a littile strange, as in image, the pretrained weight's performance using contrastive learning  is comparable with pretrained weight using supervised learning, and is much better than train from scratch. Do you think the reason is pretrain data is not enough or the method problem? Maybe you can add a experiment that pretrain model on waymodataset using supervised learning and compare the result with contrastive learning.

**Comment by zaiweizhang** [comment]
1.It actually does not take too long because the number of training instances is smaller.
2. Usually a day for point model and maybe two days for voxel model. I do not have results on pretraining with KITTI.
3. We have not tried to train with smaller batch size. I think it might affect the performance but I am not sure. You are welcome to try it.
4. Yeah. It does not affect too much with fine-tuning on full KITTI dataset. However, with smaller number of training instances, we do see consistent performance boost. Based on our results on other 3D downstream tasks (performance boost on ScanNet, SUNRGD, S3DIS and etc.), I think that maybe people have found effective data augmentation methods (such as random sample objects and put them back in the scene) to reduce this lack of data issue to the minimum. Also, another reason might be that our data augmentations in the pretraining are not strong enough. Overall, this is a simple baseline. I would happy to see follow-up work on this to improve the pretraining performance in lidar pointclouds detection.

**Comment by baraujo98** [comment]
Hi @zaiweizhang, thanks for the insight. Can you describe what the framework is expecting, to adapt correctly the extaction script? As much as I understood, I have to generate a .npy file which consists of a list of paths to each individual frame of the training data. And each frame is a numpy file with a list of the points. Is that is? I've not found a repository with a script performing a extraction similar to yours for KITTI (might be my fault).

**Comment by zaiweizhang** [comment]
Yes. A .npy file consists of a list of paths to each individual frame and each frame is a numpy file containing the pointcloud. You can refer to this [repo](https://github.com/open-mmlab/OpenPCDet/blob/master/docs/GETTING_STARTED.md) for data extraction. The end results are not exactly the same but you will just need to write some simple data processing script to convert it the desired format.

**Comment by baraujo98** [comment]
Hi @zaiweizhang. I wish to re-open, as I'm now starting to dig deeper into the code to do this adaptation. So: can I simply adapt the data loader to load a .bin instead if a .npy and give the framework a .npy list with the paths to all point clouds? My question if there is any more pre-processing required, maybe concerning calibration. Thanks

**Comment by zaiweizhang** [comment]
"adapt the data loader to load a .bin instead if a .npy and give the framework a .npy list with the paths to all point **clouds"**.
Yes. You can do this. We do not require other calibration.

**Comment by baraujo98** [comment]
I'm pretraining on KITTI, using the same hyperparameters from `point_within_lidar_template.yaml`.
Does this loss progress seem normal? Given your experience training this model, is it possible to conclude anything from this? I'm going to train on a limited number of labels next, to actually evaluate the effictiveness of this pretraining.
![image](https://user-images.githubusercontent.com/47788309/113729712-2bbba500-96ef-11eb-963a-70a9d153e456.png)

**Comment by zaiweizhang** [comment]
No. This does not look good. Usually the loss should gradually decrease and then converge. Since KITTI has only a few training instances, I would suggest that you train it much longer. At least to the point that the loss gradually decrease and converge.

**Comment by baraujo98** [comment]
Will definitely try! Without the loss decreasing and converging, it doesn't make much sense for the pretraing to be useful. I hope KITTI isn't too small and causing overfitting. I noticed you define spatial bounds for the Waymo point clouds: could that help? I think probably not...

**Comment by zaiweizhang** [comment]
Great point! The spatial bounds are specifically set for Waymo point clouds. You might need to tune it for KITTI. That actually may change the results.

**Comment by zaiweizhang** [comment]
[Here](https://github.com/open-mmlab/OpenPCDet/blob/master/tools/cfgs/dataset_configs/kitti_dataset.yaml) is a dataset config for KITTI. Please try to change the voxel size as well. And please try to visualize it before training. Just to make sure there are no bugs.

**Comment by zaiweizhang** [comment]
I am going to keep this issue open. Feel free to post any results and more questions.

**Comment by baraujo98** [comment]
Thanks, I will take a deep look at that and keep you up to date!

**Comment by AndyYuan96** [comment]
> [Here](https://github.com/open-mmlab/OpenPCDet/blob/master/tools/cfgs/dataset_configs/kitti_dataset.yaml) is a dataset config for KITTI. Please try to change the voxel size as well. And please try to visualize it before training. Just to make sure there are no bugs.

Hi，zaiwei，why you use so small batchsize for experiment of lidar point cloud which is 16 or 24，but big batchsize 1024 for sunrgb。

**Comment by zaiweizhang** [comment]
Sorry for mis-understanding. That config file is from some other github repo. I showed it here mainly because I would like to show how other projects are setting the voxel size, spatial bounds, number of points and etc. The batch size and training details should still use the original setting in our github.

**Comment by AndyYuan96** [comment]
> Sorry for mis-understanding. That config file is from some other github repo. I showed it here mainly because I would like to show how other projects are setting the voxel size, spatial bounds, number of points and etc. The batch size and training details should still use the original setting in our github.

“We use batch size 24 for PointRCNN and batch size 16 for Part A2” in your paper，last page。

**Comment by zaiweizhang** [comment]
That's for KITTI finetuning. We use batch size 1024 in pretraining for large datasets, such as scannet, redwood, waymo. However, for fine-tuning, we use the default setting in the baseline works, such as 16 for scannet and sunrgbd, 24 and 16 for KITTI.

**Comment by baraujo98** [comment]
Just checking if I'm not missing something @zaiweizhang:

1. You define the Waymo limits as `POINT_RANGE = np.array([  0. , -75. ,  -3. ,  75.0,  75. ,   3. ], dtype=np.float32)`. So apparently you are not using the points behind the car, as the minimum x-coordinate is 0. Is there a reason for this? OpenPCDet uses `[0, -40, -3, 70.4, 40, 1]`, but they are only interested in getting the points visible in the FOV. I'm planning on trying `[ -75, -75, -3, 75, 75, 2 ]`.

2. I suppose your results from training on Waymo achieved with a 0.5 gain in each one of the 4 losses, am I correct? Or the same gain for all losses. The provided Waymo config files only use the within format loss.

3. Setting the voxel size to `[0.05, 0.05, 0.1]` (8 times smaller than yours), according to PCDet. No question here, let's see if it yields good results :)

4. I didn't totally understand 2 augmentation techniques you used: `randomcuboidLidar` and `ToTensorLidar`. What is the idea behind them?

**Comment by zaiweizhang** [comment]
@baraujo98 
1. This is basically to reduce the domain difference between waymo dataset and KITTI dataset.
2. What do you mean by 4 losses? Using 100% data for fine-tuning, we are able to achieve improvements with point cloud based methods such as PointRCNN on cyclist datasets. On other categories, the gains are not significant.
3. ToTensorLidar is not a data augmentation. It's just to converge numpy to torch tensor. randomcuboidLidar is basically trying to crop the scenes from the original scene, similar to image cropping done in 2D domain pretraining. It's actually a crucial step.

**Comment by baraujo98** [comment]
@zaiweizhang 
1. Ok, makes sense. So you think the points behind the car should be discarded from a self-supervised pretraining? I've been precisely thinking about this question, and I think there's nothing wrong with including them. The domain difference between the points in front and behind a car should be very small in a normal urban driving environment, in the context of object detection, wouldn't you agree?
2. Sorry, I think I explained badly. I was talking about the weights associated with each loss (the 2 within and the 2 across format losses). I guess you used the same weight for them all, when pretraining with Waymo, is that it?
3. Nice! Got it

**Comment by baraujo98** [comment]
Hi, so I tried training with both points and voxels for KITTI and got an error. Here is the log ([log.txt](https://github.com/facebookresearch/DepthContrast/files/6289085/log.txt)), also containing all the configurations. The only code I changed was regarding the loading of point clouds, to adapt to KITTI, so that's not the source of the bug, I believe.

The command I ran: `python main.py configs/point_vox_kitti.yaml --multiprocessing-distributed --world-size 1 --rank 0 --ngpus 1` 

Do you know why this might be happening? Meanwhile, I'm *trying* to visualize the point clouds to be sure they are being well delivered.

**Comment by zaiweizhang** [comment]
So. Did you visualize your point clouds? It might happen due to no voxels in the input. "return torch.max_pool1d(
RuntimeError: stride should not be zero" This seems to be saying that "temp_f.shape[-1]" is zero, which means there are no input voxels.

**Comment by baraujo98** [comment]
@zaiweizhang I tried visualizing the last point cloud loaded before an error arises. They always looked normal, I think: here's an example. This was done with the function you wrote in `augment3d.py` called `write_ply_color()`, just slightly tweaked. The visualization is from the point cloud after the augmentations and before converting to tensor. 

![Screenshot from 2021-04-12 05-31-13](https://user-images.githubusercontent.com/47788309/114342219-62f8de80-9b53-11eb-9323-7d616a492def.png)

I'm not sure how to better visualize point clouds and voxels. I actually don't know how to visualize the voxels. I tried checking the data in the voxel structure (throught the VSCode debugging panel) and even when the system broke, I did confirm that there were voxels defined. I'm a bit stuck... Do you have any more specific suggestions as to where I should be looking to to debug this?

Things I noticed:
- The moment when the error occurs varies with batch size and nr of workers. When I choose more workers and bigger batch sizes, the networks performs a dozen of iterations, before breaking. For batchsize=1 and nr of workers=1, it breaks immediately.
- In one of the tests, I tried using your original spatial bounds, to check if the bounds were affecting this bug. The network performed some more iteration, but stopped nonetheless.
- The error is not always the same. Sometimes (usually with fewer workers) it is:
```-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/baraujo/.conda/envs/dc/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/baraujo/DepthContrast/main.py", line 123, in main_worker
    run_phase('train', train_loader, model, optimizer, train_criterion, epoch, args, cfg, logger, tb_writter)
  File "/home/baraujo/DepthContrast/main.py", line 152, in run_phase
    embedding = model(sample)
  File "/home/baraujo/.conda/envs/dc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/baraujo/.conda/envs/dc/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 617, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/home/baraujo/.conda/envs/dc/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 643, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/home/baraujo/.conda/envs/dc/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 36, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/home/baraujo/.conda/envs/dc/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 28, in scatter
    res = scatter_map(inputs)
  File "/home/baraujo/.conda/envs/dc/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/baraujo/.conda/envs/dc/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 19, in scatter_map
    return list(map(type(obj), zip(*map(scatter_map, obj.items()))))
  File "/home/baraujo/.conda/envs/dc/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/baraujo/.conda/envs/dc/lib/python3.8/site-packages/torch/nn/parallel/scatter_gather.py", line 13, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/home/baraujo/.conda/envs/dc/lib/python3.8/site-packages/torch/nn/parallel/_functions.py", line 92, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "/home/baraujo/.conda/envs/dc/lib/python3.8/site-packages/torch/nn/parallel/comm.py", line 186, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
RuntimeError: chunk expects at least a 1-dimensional tensor```

**Comment by zaiweizhang** [comment]
The random seed defined in this framework is based on the batch size. That's why the failures are correlated with batch size there. Actually, this behavior happens to me before and it was a data issue. It will fail with a certain data point. I noticed that from the visualization, near the center area, the bottom of the point clouds are cut off completely. Is this intended? If it's not, you may want to re-consider the spatial bounds. I would suggest you check the original spatial bound for each input scene, and make sure each one has some overlapping points with the spatial bound you set, which is [ -75, -75, -3, 75, 75, 2 ].

**Comment by baraujo98** [comment]
@zaiweizhang  I think I figured it out! In `models/trunks/spconv_unet.py` you had the voxel size (and spatial bounds) hardcoded: when I changed it to match the voxel size from `datasets/depth_dataset.py`, the errors stopped.

Regarding the empty patches in the point cloud they were not intentional, and I find them rather odd. I'll try to understand what is causing them... I did not fully understand your suggestion about re-considering the spatial bounds, sorry. Here are some more pictures:

![pcs](https://user-images.githubusercontent.com/47788309/114446746-7e063580-9bc9-11eb-95c5-ab82a4c94775.jpg)

I have 2 further question now (sorry to bother so much!):
1. I'm not sure what a collator is, in this framework. Each time the framework loads a new batch, there's `points` and `vox`, the 2 different data representation. But what are `points_moco` and `vox_moco`?
2. Did you have ever got an error from `spconv` while using a batch size of 32 for your Waymo training. If I try 16 or 32, there's an assertion from `spconv` that fails: `batchSize * outputVolume < std::numeric_limits<int>::max() assert faild. due to limits of cuda hash, the volume of dense space include batch size must less than std::numeric_limits<int>::max() = 2e9`. From what I understand, I don't think this has to do with capacity of my GPU, but I might be wrong...

**Comment by baraujo98** [comment]
@zaiweizhang I read the paper again and reviewed the code, and I think those deleted patches of points in the ground are intended, and part of the augmentation technique. This is done by the `randomdrop` augmentation, and this behaviour is described in the paper.

**Comment by zaiweizhang** [comment]
Good that you figured it out! That was not a good coding style for me:) About the deleted patches, it makes sense but you might want to tune the parameters a bit since those parameters were set for waymo.
1. The collator is used to define a customized function for batch processing. For the voxel representation, traditional concatenation does not work well because each scene has different number of voxels. That's why you need to define a customized collator. Points_moco and vox_moco are inputs used for momentum encoder in this [paper](https://arxiv.org/pdf/1911.05722.pdf).
2. For this question, it looks like you have too many voxels in your training data and they are reaching the limit of spconv. I would suggest you to increase the voxel size or set a smaller spatial bound to get fewer points in each scene.

**Comment by baraujo98** [comment]
Thanks @zaiweizhang! I will read the paper. I think I'll see if I can reduce a bit the spatial bounds, because it might be better to keep the typical [0.05,0.05,0.1] voxels for KITTI. 

As for the deleted patches, where do you feel I should tune them? Because they are scaled relative to the pointcloud size, I don't know how to further tune them. I've read some research that concluded that removing the entire ground from point clouds sometimes decreases the performance, for supervised training at least (https://arxiv.org/abs/2004.01643). I've never seen this patch deletion technique. Did you use this particular augmentation technique based on the results from another research work?

By the way, I've already trained for 30 epochs, and the loss is steadly decreasing! :tada::tada:
Maybe the multiple format combined training is the crucial feature, because the last training I performed was not doing that.

**Comment by zaiweizhang** [comment]
RandomCuboidCrop is very commonly used in 2D self-supervised training and RandomDrop is something I found useful for my case. It supposes to force the network to learn or infer local missing features. Since you have fewer training instances, I would actually suggest you try more aggressive data augmentation. For example, try deleting more patches or dropping more points. You should look at the fine-tuning performances and then tune your data augmentation techniques.

**Comment by baraujo98** [comment]
Ok! I really don't have the computational resources to do a lot of experimenting (only using 1 V100). But good news, the pretraining is apparently going well, by the looks of the loss evolution at least. At epoch 70 I made the data augmetation more aggressive, and at 90, even more so, hence the sudden jumps. I also reset the optimizer with a smaller lr (0.015) and larger weight decay (0.01) now, as the training appeared to be converging and the lr was very high still (0.04).

I tuned `randomcuboidLidar` to produce smaller pointclounds, I'm now dropping 3 patches, added a bit of randomness to the size and orientation of patches, and started doing random flips along the YZ plane also. Let's see if its not too strong.

I'm using all the training+validation point clouds though, so I think I'll have to do another pretraining later with only half the pointclouds, to make the final evaluation more fair. I'll share the results when I finish the process. :)

![image](https://user-images.githubusercontent.com/47788309/114917334-bbfb9780-9e1d-11eb-8f06-ba79f0987600.png)

**Comment by baraujo98** [comment]
Hi @zaiweizhang! This is a minor detail, but I'm curious to know if you experienced something similar. In red there's a pretrain performed with this optimizer hyper-parameters, that is apparently going well:

```optimizer
  name: sgd
  weight_decay: 0.0001
  momentum: 0.9
  nesterov: False
  num_epochs: 200
  lr
    name: cosine
    base_lr: 0.04
    final_lr: 4e-05
```
While in blue the only difference was that I increased the `weight_decay` to 0.005, lowered the `base_lr` to 0.02 and set `nesterov` to True. I tried these hyper-parameters because I think 0.04 might be too high of a lr (using a batch of 10) and the weight decay wasn't enough to noticebly reduce the lr by the end of the training (I'm currently converging at about 150 epochs). Do you think any of these change explains the inability of the blue pretrain to lower the loss? Maybe setting `nesterov` isn't a good idea. Thanks

![image](https://user-images.githubusercontent.com/47788309/115329640-7b3baf80-a18a-11eb-8fd9-3d82d053aadd.png)

**Comment by zaiweizhang** [comment]
I have only tried different learning rates but I have not seen this. However, I usually train with very large batch size. Probably for smaller batch size, learning rate and weight decay are very sensitive. I am not sure though. That's very interesting! Have you tested your pretrained model? Did you see any improvements?

**Comment by baraujo98** [comment]
Interesting indeed. For now the only result I have is from pretraing using train+val data from KITTI (so it's cheating, in a way), finetuning on PointRCNN for 8 epochs with the backbone frozen, and continuing for 62 epochs with the backbone trainable. They are very similar to yours, the most positively suprising might be the cyclist results. 

![pcs (1)](https://user-images.githubusercontent.com/47788309/115417265-642fa880-a1f0-11eb-9797-b623149d9397.png)

I'm now doing a longer pretrain with half the data (without the validation set), and also training a baseline PointRCNN with the same batchsize to do a more in-depth and fair comparison with it.

Out of curiosity, how did you decide which fine-tuning epoch to use the evaluation from? Did you present the results for the best epoch for each metric, or did you choose just use last epoch's evaluation for all metrics, for exemple?

**Comment by zaiweizhang** [comment]
I usually do a median on the last 10 epochs. This is expected. You should observe more gain from a limited number of labels. The power of self-supervised pretraining usually comes from a much larger pretraining dataset. Our approach mainly demonstrates that.
With only 5k training instances from KITTI and you are using the same data for pretraining and finetuning, I would suggest you try much more aggressive data augmentation methods or more challenging loss formulation. You want to avoid simple tasks that deep NN can easily overfit.

**Comment by baraujo98** [comment]
It makes sense. :+1: And I understand self-supervision should be done with a lot more data. In my case, I'm only using more or less 3x the point cloud data for the pretrain, because the supervised training only uses the points within the FOV. One of my points of interest is to know if using the whole point clouds in the pretrain would yield any improvement in performance.

As data augmentation goes, I'm already giving it a considerable boost, by flipping along YZ, introducing more and bigger empty patches, and reducing the size and minimum number of points in the cuboids. My ideias to step it up even more would be:
- Introduce a larger random rotation (even though I'm not sure if making the network to rotation is useful or feasible)
- Random noise, similar to what you coded in `augment3d.py`. Though it's not normally used, and there might be a reason for it, besides the addition computational cost

A different loss would be ambitious, I'll see if anything comes up to mind.

**Comment by baraujo98** [comment]
By the way, I'm having some trouble interpreting what is happening when I define a number of negative samples greater than the number os actual point clouds I have. This is a critical issue, since I only actually have 3712 point clouds to work with. Do you have an ideia?

**Comment by zaiweizhang** [comment]
Yes. So basically in self-supervised learning, let's say we have N data instances. For each training step(assume batch size is 1), we take 1 data from N, and apply data augmentation, and compare feature extracted from the augmented version with the rest of data instances, which maximum size is N - 1. Semantically, this makes sense because you know for sure there are N different data instances, and you can claim that from N, 1 is positive and N-1 are negatives.

However, in your case, you will compare with more than N-1 instances, and in my implementation, it will start to include features extracted from different augmented versions of the N data instances. So in your training step, it's possible that you are comparing the extracted feature from three or more augmented views and you are saying that 1 pair is positive and the other pairs are negative. This will introduce controversy.

**Comment by baraujo98** [comment]
Hi @zaiweizhang! Hope everything is ok. I have a bit of a question, and wondering you have some insight about it. 

First of all, sorry but I don't have a lot of results on KITTI to show right now (my trains are very slow). I only know the pretraining is not making much difference with the finetuning is done with 100% of labels - it only generates an interesting gain in the pedestrian AOS and image metrics. I'm pretraining for 800 epochs. I will share more results soon.

So, the question: I'm performing pretrainings with varying degrees of augmentations. I introduced random noise, and decided to do something similiar to your `randomnoise` augmenation for indoors: I don't apply it when the pointcloud is to be voxelized. I thought it made sense as the voxelization would probably attenuate the noise anyways. Everything ok!

Then I tried introducing elastic distortion (actually reutilizing some code you had written). If I don't apply this to the soon-to-be voxelized point clouds (only augmentating the `data` and `data_moco` inputs), everything's fine. Bu if I apply it to all inputs, all kind of errors appear. The errors change depending on the distortion parameters and the order I assign to the augmentation techniques. Some of them are:

`RuntimeError: size of dimension does not match previous size, operand 1, dim 0` (from torch)
`RuntimeError: stride should not be zero` (from torch)
`RuntimeError: CUDA error: an illegal memory access was encountered` (from spconv)

Do you have any idea why is this? It's more of a curiosity of mine. Here's a picture before and after the elastic distortion I'm performing, to help visualize.

![elastic](https://user-images.githubusercontent.com/47788309/118380701-b8555f00-b5db-11eb-8f05-44ebac236702.png)

**Comment by zaiweizhang** [comment]
What do you mean by applying it all inputs, would you mind telling me which variables?

**Comment by baraujo98** [comment]
> What do you mean by applying it all inputs, would you mind telling me which variables?

Each time a pointcloud is loaded, i believe, it is augmentated 4 times, creating 4 different input pointclouds: `data`, `data_moco`, `vox` and `vox_moco`, which will result in the 4 embeddings you describe in the paper. So when I wrote "soon-to-be voxelized pointclouds" I'm referring to `vox` and `vox_moco`.

**Comment by baraujo98** [comment]
For example, the line where I noticed you only tried to apply random noise to `data` and `data_moco` is [here](https://github.com/facebookresearch/DepthContrast/blob/e3a2a8a8fa3588813f258294f28f69e66d764a89/datasets/transforms/augment3d.py#L221), because you only applied it if vox==False. And vox==True only when augmentating `vox` ([here](https://github.com/facebookresearch/DepthContrast/blob/e3a2a8a8fa3588813f258294f28f69e66d764a89/datasets/depth_dataset.py#L226)) and `vox_moco` ([here](https://github.com/facebookresearch/DepthContrast/blob/e3a2a8a8fa3588813f258294f28f69e66d764a89/datasets/depth_dataset.py#L233)).

**Comment by zaiweizhang** [comment]
Yeah. Because random noise does not work very well for voxel. So you mean you apply it before this [line](https://github.com/facebookresearch/DepthContrast/blob/e3a2a8a8fa3588813f258294f28f69e66d764a89/datasets/depth_dataset.py#L230), and apply it in the get_transform3d() function. It will stop working. Did you visualize the data that causing the trouble? Looking at the error messages, I feel like after the augmentation, some pointclouds are empty. I am not sure how you implemented or used the elastic distortion. I have not used it myself. Sorry that I cannot provide much experience with it.

**Comment by baraujo98** [comment]
Yes, I implemented elastic distortions inside the get_transform3d() function. The code was copied from you with only small tweaks, [from here](https://github.com/facebookresearch/DepthContrast/blob/e3a2a8a8fa3588813f258294f28f69e66d764a89/datasets/transforms/transforms.py#L192). I tested different granularities and magnitudes and visualized some results: they were always similar to the image I showed you above, I didn't encounter any empty pointclouds.

I solved the problem by not applying these distortion to `vox` and `vox moco`, but I'm not sure why that was needed. In get_transform3d() I added:

```python
for transform_config in input_transforms_list:
    
    # other transformations you wrote here
    
    if (transform_config['name'] == 'elasticdistortion') and (vox == False):
        # I defined the parameters in the config file
        gran,magn = transform_config['granularity'], transform_config['magnitude']
        point_cloud[:,0:3] = elastic_distortion(point_cloud[:,0:3],gran,magn)
    
    # more transformations here
```
No problem, if you didn't experiment this issue! Thanks for the help

**Comment by baraujo98** [comment]
Hi @zaiweizhang, I'd like to show you the results I got from pretraining on KITTI. I can later share them here to make them openly available. Would you be interested? I can send it you through mail, Telegram, LinkedIn, or any other platform of your choosing.

**Comment by zaiweizhang** [comment]
Yeah. I am very interested. Let's do email: zaiweizhang@utexas.edu

**Comment by yinjunbo** [comment]
@zaiweizhang , hello, I'd like to know is SyncBN a necessity in contrastive learning. Since MoCo used SyncBN, but I didn't find related implementation in your code.

**Comment by zaiweizhang** [comment]
I have it for point inputs. For voxel inputs, I have implemented it and tried it during training. The results are not so good and I have commented it out. If you want, you can uncomment it and try it yourself. Here is where the codes are: https://github.com/facebookresearch/DepthContrast/blob/f2b51cc06006893055da10e42a60b78c1788a607/models/base_ssl3d_model.py#L120

**Comment by yinjunbo** [comment]
As far as I understand, this is the code for ShufflingBN, a particular implementation in MoCo, but I mean the Synchronized-BN used for multi-gpu training, which is a key component in object dectection.

**Comment by yinjunbo** [comment]
@zaiweizhang By the way, for pre-training in waymo, which batch size should be adpoted? In the cross format(voxel&point) config, you set it as 32, but in the within format(point) config you set it as 8. Besides, is the base_lr 0.12 coresponds to the batch size 32?

**Comment by zaiweizhang** [comment]
For my experiments, I used a total batch size of 1024, where each GPU maintains batch size of 32. In general, the larger batch size seems to provide better results. 0.12 is for batch size 32.

**Comment by baraujo98** [comment]
> @baraujo98, hi, have you acheived obvious improvements on KITTI with a KITTI/Waymo-pretrained model?

Hi, I tried pretraining with KITTI train set with stronger augmentations, finetuning in the KITTI train set, and evaluating in KITTI validation set. The results are not obvious, it sometimes outperformed and sometimes underperformed relative to the trained-from-scratch baseline. I pretrained for 800 epochs, and used batchsize of 10 for both pretraining and finetuning. I can send you the results if you are interested

**Comment by yinjunbo** [comment]
@zaiweizhang . So the default config for pre-training uses batch size of 32. Does the number of batch size have a obviou affect on the quality of pretrained model? Besides, it seems that this code have not supported the syncBN yet?

**Comment by yinjunbo** [comment]
> > @baraujo98, hi, have you acheived obvious improvements on KITTI with a KITTI/Waymo-pretrained model?
> 
> Hi, I tried pretraining with KITTI train set with stronger augmentations, finetuning in the KITTI train set, and evaluating in KITTI validation set. The results are not obvious, it sometimes outperformed and sometimes underperformed relative to the trained-from-scratch baseline. I pretrained for 800 epochs, and used batchsize of 10 for both pretraining and finetuning. I can send you the results if you are interested

Ok, please send to yinjunbocn@gmail.com. I'm also working to improve the pre-trained model on KITTI. We could then keep in touch.

**Comment by nuneslu** [comment]
@baraujo98 I've just seen this issue and I want to ask, could you also send me the results? I have done my own implementation of DepthContrast to pretrain on KITTI but now I'm also trying to use this repo to pretrain on KITTI. If you could send me the results would be great!

lucas.peres.nunes@gmail.com
